version: '3'

services:

  keycloak-db:
    image: docker.io/bitnami/mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_DATABASE=esm_keycloak

  keycloak:
    image: bitnami/keycloak:25.0.2
    ports:
      - "8403:8080"
    environment:
      - KEYCLOAK_CREATE_ADMIN_USER=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_DATABASE_VENDOR=mysql
      - KEYCLOAK_DATABASE_HOST=keycloak-db
      - KEYCLOAK_DATABASE_PORT=3306
      - KEYCLOAK_DATABASE_USER=mysql
      - KEYCLOAK_DATABASE_PASSWORD=mysql
      - KEYCLOAK_DATABASE_NAME=esm_keycloak
      - KEYCLOAK_JDBC_DRIVER=mysql
      - KC_DB=mysql
      - KC_DB_URL=jdbc:mysql://keycloak-db:3306/esm_keycloak
      - KC_DB_URL_HOST=keycloak-db
      - KC_DB_URL_PORT=3306
      - KC_DB_URL_DATABASE=es_keycloak
      - KC_DB_USERNAME=mysql
      - KC_DB_PASSWORD=mysql
      - KEYCLOAK_EXTRA_ARGS=--import-realm
    volumes:
      - ./config/keycloak/realm:/opt/bitnami/keycloak/data/import