version: '3.4'

volumes:
  keycloak-db:

services:
  krakend:
    # The :watch image restarts the service automatically when the configuration files change.
    # Do not use this image in production, it's meant to speed up your testing and development.
    image: devopsfaith/krakend:watch
    # image: devopsfaith/krakend:latest
    container_name: krakend
    command: run -d -c /etc/krakend/krakend.json
    ports:
      - "8402:8080"
    volumes:
      - ./config/krakend:/etc/krakend

  krakend-designer:
    image: devopsfaith/krakendesigner:latest
    container_name: krakend-designer
    ports:
      - "8401:80"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - "./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: krakend
      GF_SECURITY_ADMIN_PASSWORD: krakend
      GF_AUT_ANONYMOUS_ENABLED: "true"
    volumes:
      - "./config/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources"
      - "./config/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards"
      - "./config/grafana/data/dashboards:/var/lib/grafana/dashboards"

  keycloak-db:
    image: docker.io/bitnami/postgresql:latest
    volumes:
      - keycloak-db:/var/lib/postgresql/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak

  keycloak:
    image: bitnami/keycloak:25.0.2
    ports:
      - "8403:8080"
    environment:
      - KEYCLOAK_CREATE_ADMIN_USER=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_DATABASE_HOST=keycloak-db
      - KEYCLOAK_EXTRA_ARGS=--import-realm
    volumes:
      - ./config/keycloak/realm:/opt/bitnami/keycloak/data/import