{
 "title": "KrakenD - OpenTelemetry + Prometheus",
 "description": "RECOMMENDED INSTALL. KrakenD dashboard based on Prometheus integration via OpenTelemetry",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "app", "label": "Application", "query": { "query": "label_values(app)" } },
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance)" } },
   { "name": "endpoint", "label": "Endpoint", "query": { "query": "label_values(http_route)" } },
   { "name": "interval", "label": "Interval", "query": "1m,5m,15m,30m,1h,2h,1d" },
   { "name": "max_list", "label": "Max items", "query": "3,5,10,15,20" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total HTTP Requests",
   "type": "stat",
   "description": "Total incoming HTTP Requests in the selected period",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(http_server_duration_count{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$__range]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Throughput",
   "type": "stat",
   "description": "Average requests per second over the selected period",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(http_server_duration_count{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$__range])-min_over_time(http_server_duration_count{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$__range]))/ $__range_s",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Response Time",
   "type": "stat",
   "description": "The Average Response Time in the selected period",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_sum{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$__range])) / (sum(rate(http_server_duration_count{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$__range]))+0.0001)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Proxy Requests",
   "type": "stat",
   "description": "Total number of proxy requests",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(krakend_proxy_duration_count{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$__range]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Backend Requests",
   "type": "stat",
   "description": "Total number of attempted connections  to backends (failed or not)",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(krakend_backend_duration_count{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$__range]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg memory in use",
   "type": "stat",
   "description": "Average allocated memory per instance",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(go_memstats_alloc_bytes{app=~\"$app\", instance=~\"$instance\"}[$__range]))/count(max_over_time(go_memstats_alloc_bytes{app=~\"$app\", instance=~\"$instance\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Reserved memory",
   "type": "stat",
   "description": "An average of the total memory reserved per instance in the period",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(go_memstats_sys_bytes{app=~\"$app\", instance=~\"$instance\"}[$__range]))/count(max_over_time(go_memstats_sys_bytes{app=~\"$app\", instance=~\"$instance\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Go Routines",
   "type": "stat",
   "description": "Total number of Go routines (internal threads) running in the gateway per instance. Go routines manage the incoming traffic, background operations and other maintenance tasks.",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(go_goroutines{app=~\"$app\", instance=~\"$instance\"}[$__range]))/count(max_over_time(go_goroutines{app=~\"$app\", instance=~\"$instance\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Worst latency",
   "type": "stat",
   "description": "The worst latency seen during the selected time",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by(le) (rate(http_server_duration_bucket{app=~\"$app\", instance=~\"$instance\",http_route=~\"$endpoint\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency  p99",
   "type": "stat",
   "description": "The percentile 99 tells you that 99% of  HTTP server requests have a latency below this number.",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_server_duration_bucket{app=~\"$app\", instance=~\"$instance\",http_route=~\"$endpoint\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency  p95",
   "type": "stat",
   "description": "The percentile 95 tells you that 95% of  HTTP server requests have a latency below this number.",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_duration_bucket{app=~\"$app\", instance=~\"$instance\",http_route=~\"$endpoint\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency  p90",
   "type": "stat",
   "description": "The percentile 90 tells you that 90% of  HTTP server requests have a latency below this number.",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by(le) (rate(http_server_duration_bucket{app=~\"$app\", instance=~\"$instance\",http_route=~\"$endpoint\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency  p75",
   "type": "stat",
   "description": "The percentile 75 tells you that 75% of  HTTP server requests have a latency below this number.",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(http_server_duration_bucket{app=~\"$app\", instance=~\"$instance\",http_route=~\"$endpoint\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency  p50",
   "type": "stat",
   "description": "The percentile 50 tells you that 50% of  HTTP server requests have a latency below this number.",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_server_duration_bucket{app=~\"$app\", instance=~\"$instance\",http_route=~\"$endpoint\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg data throughput",
   "type": "stat",
   "description": "Average response size of data payloads per second in the selected period",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_response_size_sum{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$interval]))",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "Response Status Codes Distribution",
   "type": "piechart",
   "description": "Pie chart of status codes.",
   "gridPos": { "h": 12, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(http_response_status_code) (delta(http_server_duration_count{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput (RPS)",
   "type": "timeseries",
   "description": "Numer of request per second received",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$interval]))",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "Avg Latency",
   "type": "timeseries",
   "description": "Average response latency",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_sum{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$interval]))/count(max_over_time(http_server_duration_sum{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latencies (Percentile)",
   "type": "timeseries",
   "description": "The percentiles tell you the percentage of requests that responded within a time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (delta(http_server_duration_bucket{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$interval])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (delta(http_server_duration_bucket{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (delta(http_server_duration_bucket{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (delta(http_server_duration_bucket{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$interval])))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (delta(http_server_duration_bucket{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$interval])))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Response data size  (payloads)",
   "type": "timeseries",
   "description": "Bytes sent in body responses during the selected period. Headers excluded.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_response_size_sum{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$interval]))",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "Avg reponse data size (payloads)",
   "type": "timeseries",
   "description": "Average response size of data payloads in the selected period",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_response_size_sum{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$interval]) / (1 +rate(http_server_response_size_count{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$__rate_interval])))",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "Worst proxy latency",
   "type": "stat",
   "description": "The worst proxy execution has a latency matching this number",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by(le) (rate(krakend_proxy_duration_bucket{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proxy latency 99p",
   "type": "stat",
   "description": "The percentile 99 tells you that 99% of the proxy executions have a latency below this number.",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(krakend_proxy_duration_bucket{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proxy latency 95p",
   "type": "stat",
   "description": "The percentile 95 tells you that 95% of the proxy executions have a latency below this number.",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(krakend_proxy_duration_bucket{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proxy latency 90p",
   "type": "stat",
   "description": "The percentile 90 tells you that 90% of the proxy executions have a latency below this number.",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by(le) (rate(krakend_proxy_duration_bucket{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proxy latency 75p",
   "type": "stat",
   "description": "The percentile 75 tells you that 75% of the proxy executions have a latency below this number.",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(krakend_proxy_duration_bucket{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proxy latency 50p",
   "type": "stat",
   "description": "The percentile 50 tells you that 50% of the proxy executions have a latency below this number.",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(krakend_proxy_duration_bucket{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Incomplete responses per second",
   "type": "stat",
   "description": "Number of incomplete responses returned to the user on aggregation (matches X-KrakenD-Complete header)",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(krakend_proxy_duration_count{complete=\"false\",app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proxy errors per second",
   "type": "stat",
   "description": "Number of proxy errors per second seen in the selected period",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(krakend_proxy_duration_count{error=\"true\",app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Worst backend latency",
   "type": "stat",
   "description": "The worst backend connection has a latency matching this number",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(krakend_backend_duration_bucket{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend latency 99p",
   "type": "stat",
   "description": "The percentile 99 tells you that 99% of the backend connections have a latency below this number.",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(krakend_backend_duration_bucket{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend  latency 95p",
   "type": "stat",
   "description": "The percentile 95 tells you that 95% of the backend connections have a latency below this number.",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(krakend_backend_duration_bucket{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend latency 90p",
   "type": "stat",
   "description": "The percentile 90 tells you that 90% of the backend connections have a latency below this number.",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(krakend_backend_duration_bucket{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend latency 75p",
   "type": "stat",
   "description": "The percentile 75 tells you that 75% of the backend connections have a latency below this number.",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(krakend_backend_duration_bucket{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend latency 50p",
   "type": "stat",
   "description": "The percentile 50 tells you that 50% of the backend connections have a latency below this number.",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(krakend_backend_duration_bucket{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg backend traffic",
   "type": "stat",
   "description": "The average response size of backends within a second",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_client_response_size_sum{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\", http_response_status_code=~\"[24]\\\\d{2}\"}[$__rate_interval])/rate(http_client_response_size_count{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\",  http_response_status_code=~\"[24]\\\\d{2}\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend errors per second",
   "type": "stat",
   "description": "Number of backend errors per second seen in the selected period",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(krakend_backend_duration_count{error=\"true\",app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Throughput (RPS)",
   "type": "timeseries",
   "description": "Numer of request per second received",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_server_duration_count{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$interval])",
     "legendFormat": "{{http_request_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "Avg Latency",
   "type": "timeseries",
   "description": "Average response latency",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (http_request_method, http_route) (rate(http_server_duration_sum{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$interval]))/sum by (http_request_method, http_route) (rate(http_server_duration_count{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$interval]))",
     "legendFormat": "{{http_request_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "95p Endpoint Latencies",
   "type": "timeseries",
   "description": "The 95 percentile tells you that 95% of the requests responded within this time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, http_route, http_request_method) (rate(http_server_duration_bucket{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$interval])))",
     "legendFormat": "{{http_request_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "Avg response size per endpoint",
   "type": "timeseries",
   "description": "Bytes sent in body responses during the selected period. Headers excluded.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(http_server_response_size_sum{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$interval])",
     "legendFormat": "{{http_request_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "Average response size per endpoint",
   "type": "bargauge",
   "description": "Average bytes sent in body responses for each endpoint during the selected period. Headers excluded.",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(http_server_response_size_sum{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$interval]) / rate(http_server_response_size_count{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$interval])",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "Total response size per endpoint (top $max_list)",
   "type": "table",
   "description": "Bytes sent in body responses during the selected period. Headers excluded.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk($max_list, histogram_quantile(0.95, sum by (le, http_route) (rate(http_server_response_size_bucket{app=~\"$app\", instance=~\"$instance\"}[$__range])))) >= 0",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "Fastest p95 endpoints (top $max_list)",
   "type": "table",
   "description": "Fastest endpoints to respond",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "bottomk($max_list, histogram_quantile(0.95, sum by (le, http_route) (rate(http_server_duration_bucket{app=~\"$app\", instance=~\"$instance\", http_route!=\"\"}[$__range])))) >= 0",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "Slowest p95 endpoints (top $max_list)",
   "type": "table",
   "description": "Slowest endpoints to respond",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk($max_list, histogram_quantile(0.95, sum by (le, http_route) (rate(http_server_duration_bucket{app=~\"$app\", instance=~\"$instance\", http_route!=\"\"}[$__range])))) >= 0",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "Response Status Codes",
   "type": "timeseries",
   "description": "Count of HTTP response status codes over time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(http_response_status_code) (delta(http_server_duration_count{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Status Codes",
   "type": "timeseries",
   "description": "Distribution of status codes over time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(http_response_status_code) (delta(http_server_duration_count{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency Heat Map",
   "type": "heatmap",
   "description": "Histogram showing the latency of responses over time.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 94 },
   "targets": [
    {
     "expr": "sum(increase(http_server_duration_bucket{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$__interval])) by (le)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Size Heat Map",
   "type": "heatmap",
   "description": "Histogram showing the size of payloads of responses over time.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 94 },
   "targets": [
    {
     "expr": "sum(increase(http_server_response_size_bucket{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$__interval])) by (le)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Proxy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 106 } },
  {
   "title": "Throughput (RPS)",
   "type": "timeseries",
   "description": "Numer of request per second received",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(krakend_proxy_duration_count{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$interval])",
     "legendFormat": "{{http_request_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "Avg Endpoint Latencies",
   "type": "timeseries",
   "description": "The Endpoints Average Latency",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (http_request_method, http_route) (rate(krakend_proxy_duration_sum{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$interval]))/sum by (http_request_method, http_route) (rate(krakend_proxy_duration_count{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$interval]))",
     "legendFormat": "{{http_request_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "95p Endpoint Latencies",
   "type": "timeseries",
   "description": "The Endpoint p95 Latencies",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, http_route, http_request_method) (rate(krakend_proxy_duration_bucket{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$__rate_interval])))",
     "legendFormat": "{{http_request_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "Fastest endpoints (p95 - top $max_list)",
   "type": "table",
   "description": "Fastest endpoints by looking at the percentile 95",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "bottomk($max_list, histogram_quantile(0.95, sum by (le, http_route) (rate(krakend_proxy_duration_bucket{app=~\"$app\", instance=~\"$instance\"}[$__range])))) >= 0",
     "legendFormat": "{{url_path}}"
    }
   ]
  },
  {
   "title": "Slowest endpoints (p95 - top $max_list)",
   "type": "table",
   "description": "Slowest endpoints by looking at the percentile 95",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk($max_list, histogram_quantile(0.95, sum by (le, http_route) (rate(krakend_proxy_duration_bucket{app=~\"$app\", instance=~\"$instance\", http_route!=\"\"}[$__range])))) >= 0",
     "legendFormat": "{{url_path}}"
    }
   ]
  },
  {
   "title": "Latency Heat Map",
   "type": "heatmap",
   "description": "The latency heatmap",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 131 },
   "targets": [
    {
     "expr": "sum(increase(krakend_proxy_duration_bucket{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$__interval])) by (le)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Backends", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 144 } },
  {
   "title": "Throughput (RPS)",
   "type": "timeseries",
   "description": "Number of BACKEND request per second executed",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_client_duration_count{app=~\"$app\", instance=~\"$instance\", krakend_endpoint_route=~\"$endpoint\"}[$interval])",
     "legendFormat": "{{http_request_method}} {{server_address}}{{http_route}}"
    }
   ]
  },
  {
   "title": "Avg requests latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 156 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(http_request_method, http_route, server_address) (rate(http_client_duration_sum{app=~\"$app\", instance=~\"$instance\", krakend_endpoint_route=~\"$endpoint\"}[$__rate_interval]))/sum by(http_request_method, http_route, server_address) (rate(http_client_duration_count{app=~\"$app\", instance=~\"$instance\", krakend_endpoint_route=~\"$endpoint\"}[$__rate_interval]))",
     "legendFormat": "{{http_request_method}} {{server_address}}{{http_route}}"
    }
   ]
  },
  {
   "title": "95p Backend Request Duration",
   "type": "timeseries",
   "description": "The time it takes for a request to have the first byte of the response body ready to be read.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 156 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, http_route, http_request_method, server_address) (rate(http_client_duration_bucket{app=~\"$app\", instance=~\"$instance\", krakend_endpoint_route=~\"$endpoint\"}[$__rate_interval])))",
     "legendFormat": "{{http_request_method}} {{server_address}}{{http_route}}"
    }
   ]
  },
  {
   "title": "Received Content Length",
   "type": "timeseries",
   "description": "Number of bytes reported by consumed responses Content-Length values. In case of chunked responses, the metrics are not displayed here.",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 167 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(http_client_response_size_sum{app=~\"$app\", instance=~\"$instance\", krakend_endpoint_route=~\"$endpoint\"}[$interval])",
     "legendFormat": "{{http_request_method}} {{server_address}}{{http_route}}"
    }
   ]
  },
  {
   "title": "No Content Length Count",
   "type": "timeseries",
   "description": "Backends that did not report a Content-Length header",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 167 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(http_client_response_no_content_length_total{app=~\"$app\", instance=~\"$instance\", krakend_endpoint_route=~\"$endpoint\"}[$interval])",
     "legendFormat": "{{http_request_method}} {{server_address}}{{http_route}}"
    }
   ]
  },
  {
   "title": "Average Content Length",
   "type": "timeseries",
   "description": "Average response content-lenght. Chunked responses are not taken into account.",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 167 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(http_client_response_size_sum{app=~\"$app\", instance=~\"$instance\", krakend_endpoint_route=~\"$endpoint\"}[$interval]) / rate(http_client_response_size_count{app=~\"$app\", instance=~\"$instance\", krakend_endpoint_route=~\"$endpoint\"}[$interval])",
     "legendFormat": "{{http_request_method}} {{server_address}}{{http_route}}"
    }
   ]
  },
  {
   "title": "Read Content Size",
   "type": "timeseries",
   "description": "Number of bytes readed from the body. In case a cancel, or a closed connection, the read bytes might not match those of content-lenght. This metric includes chunked responses that do not come with the Content-Length header set.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 179 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(http_client_request_read_size_hist_sum{app=~\"$app\", instance=~\"$instance\", krakend_endpoint_route=~\"$endpoint\"}[$interval])",
     "legendFormat": "{{http_request_method}} {{server_address}}{{http_route}}"
    }
   ]
  },
  {
   "title": "Avg Read Content Size",
   "type": "timeseries",
   "description": "Average Number of bytes readed from the body. In case a cancel, or a closed connection, the read bytes might not match those of content-lenght. This metric includes chunked responses that do not come with the Content-Length header set.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 179 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(http_client_request_read_size_hist_sum{app=~\"$app\", instance=~\"$instance\", krakend_endpoint_route=~\"$endpoint\"}[$interval]) / rate(http_client_request_read_size_hist_count{app=~\"$app\", instance=~\"$instance\", krakend_endpoint_route=~\"$endpoint\"}[$interval])",
     "legendFormat": "{{http_request_method}} {{server_address}}{{http_route}}"
    }
   ]
  },
  {
   "title": "Fastest p95 endpoints (top $max_list)",
   "type": "table",
   "description": "Fastest backend response times p95",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 191 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "bottomk($max_list, histogram_quantile(0.95, sum by (le, http_route, http_request_method, server_address) (rate(http_client_duration_bucket{app=~\"$app\", instance=~\"$instance\", krakend_endpoint_route=~\"$endpoint\", http_route!=\"\"}[$__range])))) >= 0",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "Slowest p95 endpoints (top $max_list)",
   "type": "table",
   "description": "Slowest backend tesponse times p95",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 191 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk($max_list, histogram_quantile(0.95, sum by (le, http_route, server_address, http_request_method) (rate(http_client_duration_bucket{app=~\"$app\", instance=~\"$instance\", krakend_endpoint_route=~\"$endpoint\", http_route!=\"\"}[$__range])))) >= 0",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "Response Status Codes Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 199 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(http_response_status_code) (delta(http_client_duration_count{app=~\"$app\", instance=~\"$instance\", krakend_endpoint_route=~\"$endpoint\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Status Codes Distribution",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 199 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(http_response_status_code) (delta(http_client_duration_count{app=~\"$app\", instance=~\"$instance\", krakend_endpoint_route=~\"$endpoint\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency Heat Map",
   "type": "heatmap",
   "description": "The BACKEND requests latency heatmap",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 208 },
   "targets": [
    {
     "expr": "sum(increase(http_client_duration_bucket{app=~\"$app\", instance=~\"$instance\", krakend_endpoint_route=~\"$endpoint\"}[$__interval])) by (le)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Size Heat Map",
   "type": "heatmap",
   "description": "The Response Size Heatmap",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 208 },
   "targets": [
    {
     "expr": "sum(increase(http_client_response_size_bucket{app=~\"$app\", instance=~\"$instance\", krakend_endpoint_route=~\"$endpoint\"}[$__interval])) by (le)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed and Timed out",
   "type": "timeseries",
   "description": "Failed and timed out requests.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 221 },
   "targets": [
    {
     "expr": "sum(rate(http_client_request_failed_count_total{app=~\"$app\", instance=~\"$instance\", krakend_endpoint_route=~\"$endpoint\"}[$__rate_interval]))",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(rate(http_client_request_timedout_count_total{app=~\"$app\", instance=~\"$instance\", krakend_endpoint_route=~\"$endpoint\"}[$__rate_interval]))",
     "legendFormat": "Timed out"
    }
   ]
  },
  {
   "title": "Started vs Canceled",
   "type": "timeseries",
   "description": "Requests started vs canceled.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 221 },
   "targets": [
    {
     "expr": "sum(rate(http_client_request_started_count_total{app=~\"$app\", instance=~\"$instance\", krakend_endpoint_route=~\"$endpoint\"}[$__rate_interval]))",
     "legendFormat": "Started"
    },
    {
     "expr": "sum(rate(http_client_request_canceled_count_total{app=~\"$app\", instance=~\"$instance\", krakend_endpoint_route=~\"$endpoint\"}[$__rate_interval]))",
     "legendFormat": "Cancelled"
    }
   ]
  },
  {
   "title": "Requests Details p95",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 230 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_client_request_get_conn_duration_bucket{app=~\"$app\", instance=~\"$instance\", krakend_endpoint_route=~\"$endpoint\"}[$__rate_interval])))",
     "legendFormat": "Get Conn"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_client_request_dns_duration_bucket{app=~\"$app\", instance=~\"$instance\", krakend_endpoint_route=~\"$endpoint\"}[$__rate_interval])))",
     "legendFormat": "DNS"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_client_request_tls_duration_bucket{app=~\"$app\", instance=~\"$instance\", krakend_endpoint_route=~\"$endpoint\"}[$__rate_interval])))",
     "legendFormat": "TLS"
    }
   ]
  },
  {
   "title": "Avg Request Times",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 230 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_client_request_get_conn_duration_sum{app=~\"$app\", instance=~\"$instance\", krakend_endpoint_route=~\"$endpoint\"}[$__rate_interval]))/sum(rate(http_client_request_get_conn_duration_count{app=~\"$app\", instance=~\"$instance\", krakend_endpoint_route=~\"$endpoint\"}[$__rate_interval]))",
     "legendFormat": "Get Conn"
    },
    {
     "expr": "sum(rate(http_client_request_dns_duration_sum{app=~\"$app\", instance=~\"$instance\", krakend_endpoint_route=~\"$endpoint\"}[$__rate_interval]))/sum(rate(http_client_request_dns_duration_count{app=~\"$app\", instance=~\"$instance\", krakend_endpoint_route=~\"$endpoint\"}[$__rate_interval]))",
     "legendFormat": "DNS"
    },
    {
     "expr": "sum(rate(http_client_request_tls_duration_sum{app=~\"$app\", instance=~\"$instance\", krakend_endpoint_route=~\"$endpoint\"}[$__rate_interval]))/sum(rate(http_client_request_tls_duration_count{app=~\"$app\", instance=~\"$instance\", krakend_endpoint_route=~\"$endpoint\"}[$__rate_interval]))",
     "legendFormat": "TLS"
    }
   ]
  },
  {
   "title": "Avg backend duration",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 241 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(http_route, http_request_method, server_address) (rate(krakend_backend_duration_sum{app=~\"$app\", instance=~\"$instance\", krakend_endpoint_route=~\"$endpoint\"}[$__rate_interval]))/sum by(http_route, http_request_method, server_address) (rate(krakend_backend_duration_count{app=~\"$app\", instance=~\"$instance\", krakend_endpoint_route=~\"$endpoint\"}[$__rate_interval]))",
     "legendFormat": "{{http_request_method}} {{server_address}}{{http_route}}"
    }
   ]
  },
  {
   "title": "p95 backend duration",
   "type": "timeseries",
   "description": "Percentile 95 of backend duration",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 241 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, http_route, http_request_method, server_address) (rate(krakend_backend_duration_bucket{app=~\"$app\", instance=~\"$instance\", krakend_endpoint_route=~\"$endpoint\"}[$__rate_interval])))",
     "legendFormat": "{{http_request_method}} {{server_address}}{{http_route}}"
    }
   ]
  },
  {
   "title": "Requests Started Count",
   "type": "timeseries",
   "description": "Number of requests initiated",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 252 },
   "targets": [
    {
     "expr": " sum by (http_request_method, krakend_endpoint_route, server_address, http_route) (rate(http_client_request_started_count_total{app=~\"$app\", instance=~\"$instance\", krakend_endpoint_route=~\"$endpoint\"}[1m]))",
     "legendFormat": "{{http_request_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "Response Size p95",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 263 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_client_response_size_bucket{app=~\"$app\", instance=~\"$instance\", krakend_endpoint_route=~\"$endpoint\"}[$__rate_interval])))",
     "legendFormat": "Response Size"
    }
   ]
  },
  { "title": "Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 269 } },
  {
   "title": "GC Duration",
   "type": "timeseries",
   "description": "Time spent on garbage collection",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 270 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_sum{instance=~\"$instance\",app=~\"$app\"}[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC Per Second",
   "type": "timeseries",
   "description": "Counts of garbage collection operations per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 270 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_count{instance=~\"$instance\",app=~\"$app\"}[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC Quantiles",
   "type": "timeseries",
   "description": "Garbage collector duration quantiles",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 278 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (quantile) (rate(go_gc_duration_seconds{app=~\"$app\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "timeseries",
   "description": "Memory in use by the application over time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 286 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes{app=~\"$app\", instance=~\"$instance\"}[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Allocated Memory",
   "type": "timeseries",
   "description": "Total number of bytes allocated, even if freed.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 286 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{app=~\"$app\", instance=~\"$instance\"}[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Frees",
   "type": "timeseries",
   "description": "Total number of frees.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 294 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(go_memstats_frees_total{app=~\"$app\", instance=~\"$instance\"}[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Allocated objects",
   "type": "timeseries",
   "description": "Number of allocated objects.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 294 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(go_memstats_heap_objects{app=~\"$app\", instance=~\"$instance\"}[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Released memory",
   "type": "timeseries",
   "description": "Number of heap bytes released to OS.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 302 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(go_memstats_heap_released_bytes{app=~\"$app\", instance=~\"$instance\"}[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Heap memory",
   "type": "timeseries",
   "description": "Idle vs In Use heap memory",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 310 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(go_memstats_heap_inuse_bytes{app=~\"$app\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "in use"
    },
    {
     "expr": "sum(rate(go_memstats_heap_idle_bytes{app=~\"$app\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "idle"
    }
   ]
  },
  {
   "title": "Stack memory",
   "type": "timeseries",
   "description": "Obtained vs in use stack memory.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 318 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(go_memstats_stack_inuse_bytes{app=~\"$app\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "in use"
    },
    {
     "expr": "sum(rate(go_memstats_stack_sys_bytes{app=~\"$app\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "obtained"
    }
   ]
  },
  {
   "title": "OS Threads",
   "type": "timeseries",
   "description": "Number of OS threads created.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 326 },
   "targets": [
    {
     "expr": "avg_over_time(go_threads{app=~\"$app\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "description": "Number of live go routines.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 326 },
   "targets": [
    {
     "expr": "avg_over_time(go_goroutines{app=~\"$app\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}